#CakeShop System Config
#Fri Jun 05 14:31:52 CST 2026
site_name=CakeShop
copyright=Copyright © 2026 CakeShop. All rights reserved.
contact_phone=
hero_subtitle=精选优质原料，匠心手作蛋糕，为您的生活增添甜蜜。
hero_title=每一口都是幸福。
page_size=8
contact_email=
